# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI_template.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setWindowModality(QtCore.Qt.WindowModal)
        Dialog.resize(734, 565)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(3)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        Dialog.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        Dialog.setWindowOpacity(1.0)
        Dialog.setAutoFillBackground(True)
        self.gridLayout_2 = QtWidgets.QGridLayout(Dialog)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.canvasLay = QtWidgets.QVBoxLayout()
        self.canvasLay.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.canvasLay.setObjectName("canvasLay")
        self.gridLayout.addLayout(self.canvasLay, 6, 0, 1, 2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.gridLayout.addLayout(self.horizontalLayout, 8, 0, 1, 2)
        self.toolbarLay = QtWidgets.QVBoxLayout()
        self.toolbarLay.setObjectName("toolbarLay")
        self.gridLayout.addLayout(self.toolbarLay, 3, 0, 1, 2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.folder_1 = QtWidgets.QPushButton(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.folder_1.sizePolicy().hasHeightForWidth())
        self.folder_1.setSizePolicy(sizePolicy)
        self.folder_1.setObjectName("folder_1")
        self.horizontalLayout_2.addWidget(self.folder_1)
        self.remove_1 = QtWidgets.QPushButton(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.remove_1.sizePolicy().hasHeightForWidth())
        self.remove_1.setSizePolicy(sizePolicy)
        self.remove_1.setMaximumSize(QtCore.QSize(30, 16777215))
        self.remove_1.setObjectName("remove_1")
        self.horizontalLayout_2.addWidget(self.remove_1)
        self.folder_status_1 = QtWidgets.QLabel(Dialog)
        self.folder_status_1.setObjectName("folder_status_1")
        self.horizontalLayout_2.addWidget(self.folder_status_1)
        self.gridLayout.addLayout(self.horizontalLayout_2, 4, 0, 1, 2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.folder_2 = QtWidgets.QPushButton(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.folder_2.sizePolicy().hasHeightForWidth())
        self.folder_2.setSizePolicy(sizePolicy)
        self.folder_2.setObjectName("folder_2")
        self.horizontalLayout_3.addWidget(self.folder_2)
        self.remove_2 = QtWidgets.QPushButton(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.remove_2.sizePolicy().hasHeightForWidth())
        self.remove_2.setSizePolicy(sizePolicy)
        self.remove_2.setMaximumSize(QtCore.QSize(30, 16777215))
        self.remove_2.setObjectName("remove_2")
        self.horizontalLayout_3.addWidget(self.remove_2)
        self.folder_status_2 = QtWidgets.QLabel(Dialog)
        self.folder_status_2.setObjectName("folder_status_2")
        self.horizontalLayout_3.addWidget(self.folder_status_2)
        self.gridLayout.addLayout(self.horizontalLayout_3, 5, 0, 1, 2)
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.logY = QtWidgets.QCheckBox(self.groupBox)
        self.logY.setObjectName("logY")
        self.gridLayout_3.addWidget(self.logY, 1, 3, 1, 1)
        self.grid = QtWidgets.QCheckBox(self.groupBox)
        self.grid.setObjectName("grid")
        self.gridLayout_3.addWidget(self.grid, 1, 2, 1, 1)
        self.dbX = QtWidgets.QCheckBox(self.groupBox)
        self.dbX.setObjectName("dbX")
        self.gridLayout_3.addWidget(self.dbX, 0, 3, 1, 1)
        self.actualiser = QtWidgets.QPushButton(self.groupBox)
        self.actualiser.setMaximumSize(QtCore.QSize(100, 16777215))
        self.actualiser.setObjectName("actualiser")
        self.gridLayout_3.addWidget(self.actualiser, 1, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 0, 0, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.groupBox)
        self.comboBox.setMaximumSize(QtCore.QSize(130, 16777215))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout_3.addWidget(self.comboBox, 0, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(50, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem, 0, 1, 1, 1)
        self.gridLayout.addWidget(self.groupBox, 7, 0, 1, 2)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Interface - Simulation numérique II"))
        self.label_2.setText(_translate("Dialog", "Mathieu Maréchal - 2019"))
        self.folder_1.setText(_translate("Dialog", "Dossier 1"))
        self.remove_1.setText(_translate("Dialog", "-"))
        self.folder_status_1.setText(_translate("Dialog", "Pas de données chargées"))
        self.folder_2.setText(_translate("Dialog", "Dossier 2"))
        self.remove_2.setText(_translate("Dialog", "-"))
        self.folder_status_2.setText(_translate("Dialog", "Pas de données chargées"))
        self.logY.setText(_translate("Dialog", "log Y"))
        self.grid.setText(_translate("Dialog", "Quadrillage "))
        self.dbX.setText(_translate("Dialog", "log X"))
        self.actualiser.setText(_translate("Dialog", "Actualiser"))
        self.label_4.setText(_translate("Dialog", "Options de tracé"))
        self.comboBox.setItemText(0, _translate("Dialog", "FRF"))
        self.comboBox.setItemText(1, _translate("Dialog", "Spectre"))
        self.comboBox.setItemText(2, _translate("Dialog", "Temporel"))

